# Generated by Django 5.0.6 on 2024-06-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='image',
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='art_images/')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='art.art')),
            ],
        ),
    ]
